OUTPUT_FORMAT("elf32-littleriscv");
OUTPUT_ARCH("riscv")

ENTRY(_start);
MEMORY {
  ROM(rx)   : ORIGIN = 0x0000, LENGTH = 16k
  RAM(rw)   : ORIGIN = 0x4000, LENGTH = 16k
}

SECTIONS
{
  .text   : { *(.text)   } > ROM
  .rodata : { *(.rodata) } > RAM
  .data   : { *(.data)   } > RAM
  .bss    : {
     _sbss = .;
     *(.bss)
     _ebss = .;
  } > RAM

  . = ORIGIN(RAM) + LENGTH(RAM);
  _stack_top = .;
}
